version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - stardb:/var/lib/postgresql/data

  api:
    image: starlink-api-init:latest
    build:
      context: .
    depends_on:
      - db
    ports:
      - 80:80
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
volumes:
  stardb:
    driver: local